charge_confusion_tracker()  {


   TCanvas *c_1 = new TCanvas("c_1", "c_1",11,34,700,500);
   c_1->Range(-475,-1870.838,4275,16837.54);
   c_1->SetFillColor(0);
   c_1->SetBorderMode(0);
   c_1->SetBorderSize(2);
   c_1->SetFrameBorderMode(0);
   c_1->SetFrameBorderMode(0);
   
   TH1F *h_length_tot = new TH1F("h_length_tot","tot",100,0,3800);
   h_length_tot->SetBinContent(2,5);
   h_length_tot->SetBinContent(3,1096);
   h_length_tot->SetBinContent(4,5724);
   h_length_tot->SetBinContent(5,7156);
   h_length_tot->SetBinContent(6,7154);
   h_length_tot->SetBinContent(7,7231);
   h_length_tot->SetBinContent(8,6682);
   h_length_tot->SetBinContent(9,6459);
   h_length_tot->SetBinContent(10,5140);
   h_length_tot->SetBinContent(11,4295);
   h_length_tot->SetBinContent(12,9932);
   h_length_tot->SetBinContent(13,14254);
   h_length_tot->SetBinContent(14,11197);
   h_length_tot->SetBinContent(15,8994);
   h_length_tot->SetBinContent(16,7413);
   h_length_tot->SetBinContent(17,6160);
   h_length_tot->SetBinContent(18,5019);
   h_length_tot->SetBinContent(19,4040);
   h_length_tot->SetBinContent(20,3511);
   h_length_tot->SetBinContent(21,3051);
   h_length_tot->SetBinContent(22,2548);
   h_length_tot->SetBinContent(23,2226);
   h_length_tot->SetBinContent(24,1863);
   h_length_tot->SetBinContent(25,1592);
   h_length_tot->SetBinContent(26,1472);
   h_length_tot->SetBinContent(27,1198);
   h_length_tot->SetBinContent(28,991);
   h_length_tot->SetBinContent(29,951);
   h_length_tot->SetBinContent(30,827);
   h_length_tot->SetBinContent(31,714);
   h_length_tot->SetBinContent(32,615);
   h_length_tot->SetBinContent(33,555);
   h_length_tot->SetBinContent(34,546);
   h_length_tot->SetBinContent(35,459);
   h_length_tot->SetBinContent(36,410);
   h_length_tot->SetBinContent(37,369);
   h_length_tot->SetBinContent(38,333);
   h_length_tot->SetBinContent(39,309);
   h_length_tot->SetBinContent(40,283);
   h_length_tot->SetBinContent(41,259);
   h_length_tot->SetBinContent(42,242);
   h_length_tot->SetBinContent(43,232);
   h_length_tot->SetBinContent(44,185);
   h_length_tot->SetBinContent(45,205);
   h_length_tot->SetBinContent(46,198);
   h_length_tot->SetBinContent(47,159);
   h_length_tot->SetBinContent(48,143);
   h_length_tot->SetBinContent(49,135);
   h_length_tot->SetBinContent(50,125);
   h_length_tot->SetBinContent(51,118);
   h_length_tot->SetBinContent(52,120);
   h_length_tot->SetBinContent(53,84);
   h_length_tot->SetBinContent(54,88);
   h_length_tot->SetBinContent(55,83);
   h_length_tot->SetBinContent(56,89);
   h_length_tot->SetBinContent(57,82);
   h_length_tot->SetBinContent(58,83);
   h_length_tot->SetBinContent(59,63);
   h_length_tot->SetBinContent(60,51);
   h_length_tot->SetBinContent(61,54);
   h_length_tot->SetBinContent(62,42);
   h_length_tot->SetBinContent(63,39);
   h_length_tot->SetBinContent(64,39);
   h_length_tot->SetBinContent(65,36);
   h_length_tot->SetBinContent(66,30);
   h_length_tot->SetBinContent(67,42);
   h_length_tot->SetBinContent(68,23);
   h_length_tot->SetBinContent(69,17);
   h_length_tot->SetBinContent(70,11);
   h_length_tot->SetBinContent(71,19);
   h_length_tot->SetBinContent(72,14);
   h_length_tot->SetBinContent(73,12);
   h_length_tot->SetBinContent(74,9);
   h_length_tot->SetBinContent(75,9);
   h_length_tot->SetBinContent(76,9);
   h_length_tot->SetBinContent(77,14);
   h_length_tot->SetBinContent(78,9);
   h_length_tot->SetBinContent(79,6);
   h_length_tot->SetBinContent(80,6);
   h_length_tot->SetBinContent(81,5);
   h_length_tot->SetBinContent(83,7);
   h_length_tot->SetBinContent(84,3);
   h_length_tot->SetBinContent(85,4);
   h_length_tot->SetBinContent(86,1);
   h_length_tot->SetBinContent(87,5);
   h_length_tot->SetBinContent(88,2);
   h_length_tot->SetBinContent(89,2);
   h_length_tot->SetBinContent(90,1);
   h_length_tot->SetBinContent(92,1);
   h_length_tot->SetEntries(145989);
   h_length_tot->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 145989 ");
   text = ptstats->AddText("Mean  =  541.4");
   text = ptstats->AddText("RMS   =  337.9");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_length_tot->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_length_tot);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_length_tot->SetLineColor(ci);
   h_length_tot->GetXaxis()->SetTitle("Electron length [mm]");
   h_length_tot->GetXaxis()->SetRange(1,100);
   h_length_tot->GetXaxis()->SetLabelFont(42);
   h_length_tot->GetXaxis()->SetLabelSize(0.035);
   h_length_tot->GetXaxis()->SetTitleSize(0.035);
   h_length_tot->GetXaxis()->SetTitleFont(42);
   h_length_tot->GetYaxis()->SetLabelFont(42);
   h_length_tot->GetYaxis()->SetLabelSize(0.035);
   h_length_tot->GetYaxis()->SetTitleSize(0.035);
   h_length_tot->GetYaxis()->SetTitleFont(42);
   h_length_tot->GetZaxis()->SetLabelFont(42);
   h_length_tot->GetZaxis()->SetLabelSize(0.035);
   h_length_tot->GetZaxis()->SetTitleSize(0.035);
   h_length_tot->GetZaxis()->SetTitleFont(42);
   h_length_tot->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("tot");
   pt->Draw();
   c_1->Modified();
   c_1->cd();
   c_1->SetSelected(c_1);

//=========  (Tue Jan 12 17:30:36 2016) by ROOT version5.34/23
   TCanvas *c_2 = new TCanvas("c_2", "c_2",11,34,700,500);
   c_2->Range(-450,-626.85,4050,5641.65);
   c_2->SetFillColor(0);
   c_2->SetBorderMode(0);
   c_2->SetBorderSize(2);
   c_2->SetFrameBorderMode(0);
   c_2->SetFrameBorderMode(0);
   
   TH1F *h_length_no_neg_charge = new TH1F("h_length_no_neg_charge","not negative charge",100,0,3600);
   h_length_no_neg_charge->SetBinContent(2,1);
   h_length_no_neg_charge->SetBinContent(3,847);
   h_length_no_neg_charge->SetBinContent(4,4539);
   h_length_no_neg_charge->SetBinContent(5,4776);
   h_length_no_neg_charge->SetBinContent(6,3840);
   h_length_no_neg_charge->SetBinContent(7,3225);
   h_length_no_neg_charge->SetBinContent(8,2543);
   h_length_no_neg_charge->SetBinContent(9,1989);
   h_length_no_neg_charge->SetBinContent(10,1526);
   h_length_no_neg_charge->SetBinContent(11,1174);
   h_length_no_neg_charge->SetBinContent(12,981);
   h_length_no_neg_charge->SetBinContent(13,2432);
   h_length_no_neg_charge->SetBinContent(14,1905);
   h_length_no_neg_charge->SetBinContent(15,1622);
   h_length_no_neg_charge->SetBinContent(16,1272);
   h_length_no_neg_charge->SetBinContent(17,1116);
   h_length_no_neg_charge->SetBinContent(18,1012);
   h_length_no_neg_charge->SetBinContent(19,874);
   h_length_no_neg_charge->SetBinContent(20,717);
   h_length_no_neg_charge->SetBinContent(21,664);
   h_length_no_neg_charge->SetBinContent(22,542);
   h_length_no_neg_charge->SetBinContent(23,474);
   h_length_no_neg_charge->SetBinContent(24,390);
   h_length_no_neg_charge->SetBinContent(25,335);
   h_length_no_neg_charge->SetBinContent(26,323);
   h_length_no_neg_charge->SetBinContent(27,292);
   h_length_no_neg_charge->SetBinContent(28,254);
   h_length_no_neg_charge->SetBinContent(29,211);
   h_length_no_neg_charge->SetBinContent(30,187);
   h_length_no_neg_charge->SetBinContent(31,182);
   h_length_no_neg_charge->SetBinContent(32,176);
   h_length_no_neg_charge->SetBinContent(33,133);
   h_length_no_neg_charge->SetBinContent(34,105);
   h_length_no_neg_charge->SetBinContent(35,104);
   h_length_no_neg_charge->SetBinContent(36,109);
   h_length_no_neg_charge->SetBinContent(37,85);
   h_length_no_neg_charge->SetBinContent(38,64);
   h_length_no_neg_charge->SetBinContent(39,77);
   h_length_no_neg_charge->SetBinContent(40,64);
   h_length_no_neg_charge->SetBinContent(41,50);
   h_length_no_neg_charge->SetBinContent(42,60);
   h_length_no_neg_charge->SetBinContent(43,55);
   h_length_no_neg_charge->SetBinContent(44,37);
   h_length_no_neg_charge->SetBinContent(45,40);
   h_length_no_neg_charge->SetBinContent(46,30);
   h_length_no_neg_charge->SetBinContent(47,30);
   h_length_no_neg_charge->SetBinContent(48,29);
   h_length_no_neg_charge->SetBinContent(49,28);
   h_length_no_neg_charge->SetBinContent(50,20);
   h_length_no_neg_charge->SetBinContent(51,17);
   h_length_no_neg_charge->SetBinContent(52,19);
   h_length_no_neg_charge->SetBinContent(53,24);
   h_length_no_neg_charge->SetBinContent(54,11);
   h_length_no_neg_charge->SetBinContent(55,17);
   h_length_no_neg_charge->SetBinContent(56,17);
   h_length_no_neg_charge->SetBinContent(57,21);
   h_length_no_neg_charge->SetBinContent(58,14);
   h_length_no_neg_charge->SetBinContent(59,11);
   h_length_no_neg_charge->SetBinContent(60,7);
   h_length_no_neg_charge->SetBinContent(61,15);
   h_length_no_neg_charge->SetBinContent(62,8);
   h_length_no_neg_charge->SetBinContent(63,11);
   h_length_no_neg_charge->SetBinContent(64,11);
   h_length_no_neg_charge->SetBinContent(65,6);
   h_length_no_neg_charge->SetBinContent(66,6);
   h_length_no_neg_charge->SetBinContent(67,5);
   h_length_no_neg_charge->SetBinContent(68,6);
   h_length_no_neg_charge->SetBinContent(69,5);
   h_length_no_neg_charge->SetBinContent(70,3);
   h_length_no_neg_charge->SetBinContent(71,3);
   h_length_no_neg_charge->SetBinContent(72,2);
   h_length_no_neg_charge->SetBinContent(73,1);
   h_length_no_neg_charge->SetBinContent(74,1);
   h_length_no_neg_charge->SetBinContent(75,5);
   h_length_no_neg_charge->SetBinContent(76,2);
   h_length_no_neg_charge->SetBinContent(78,2);
   h_length_no_neg_charge->SetBinContent(79,3);
   h_length_no_neg_charge->SetBinContent(80,1);
   h_length_no_neg_charge->SetBinContent(81,2);
   h_length_no_neg_charge->SetBinContent(82,1);
   h_length_no_neg_charge->SetBinContent(83,3);
   h_length_no_neg_charge->SetBinContent(84,1);
   h_length_no_neg_charge->SetBinContent(85,1);
   h_length_no_neg_charge->SetBinContent(87,1);
   h_length_no_neg_charge->SetBinContent(88,2);
   h_length_no_neg_charge->SetBinContent(89,2);
   h_length_no_neg_charge->SetBinContent(92,1);
   h_length_no_neg_charge->SetEntries(41809);
   h_length_no_neg_charge->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 41809  ");
   text = ptstats->AddText("Mean  =  412.8");
   text = ptstats->AddText("RMS   =  319.6");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_length_no_neg_charge->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_length_no_neg_charge);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_length_no_neg_charge->SetLineColor(ci);
   h_length_no_neg_charge->GetXaxis()->SetTitle("Electron length [mm]");
   h_length_no_neg_charge->GetXaxis()->SetRange(1,100);
   h_length_no_neg_charge->GetXaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetXaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetXaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetXaxis()->SetTitleFont(42);
   h_length_no_neg_charge->GetYaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetYaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetYaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetYaxis()->SetTitleFont(42);
   h_length_no_neg_charge->GetZaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetZaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetZaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetZaxis()->SetTitleFont(42);
   h_length_no_neg_charge->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("no charge cut");
   pt->Draw();
   c_2->Modified();
   c_2->cd();
   c_2->SetSelected(c_2);
   
   TCanvas *c_3 = new TCanvas("c_3", "c_3",11,34,700,500);
   c_3->Range(-100,-1981.481,3400,17833.33);
   c_3->SetFillColor(0);
   c_3->SetBorderMode(0);
   c_3->SetBorderSize(2);
   c_3->SetFrameBorderMode(0);
   c_3->SetFrameBorderMode(0);
   
   TH1F * h_clone_length = h_length_no_neg_charge->Clone();
   
   h_clone_length->Sumw2();
   h_length_tot->Sumw2();
   h_clone_length->Divide(h_length_tot);
   h_clone_length->SetMarkerStyle(8);
   h_clone_length->SetLineColor(kBlack);
   h_clone_length->SetLineWidth(2);
   h_clone_length->GetYaxis()->SetTitle("Charge confusion");
   h_clone_length->GetXaxis()->SetLabelSize(0.05);
   h_clone_length->GetYaxis()->SetLabelSize(0.05);
   h_clone_length->GetXaxis()->SetTitleSize(0.05);
   h_clone_length->GetYaxis()->SetTitleSize(0.05);
   h_clone_length->GetYaxis()->SetTitleOffset(1.3);
   h_clone_length->GetYaxis()->SetRangeUser(0,1.1);
   
   c_3->cd();
   c_3->SetGridx();
   c_3->SetGridy();
   h_clone_length->Draw();
   c_3->Update();
   
   

   
   
   /////////////////////////////////////////////////////////////////////////////////
   
   
   TCanvas *c_energy_tot = new TCanvas("c_energy_tot", "c_energy_tot",11,34,700,500);
   c_energy_tot->Range(-0.43125,-779.4938,3.88125,7015.444);
   c_energy_tot->SetFillColor(0);
   c_energy_tot->SetBorderMode(0);
   c_energy_tot->SetBorderSize(2);
   c_energy_tot->SetFrameBorderMode(0);
   c_energy_tot->SetFrameBorderMode(0);
   
   TH1F *h_energy_tot = new TH1F("h_energy_tot","_energy",100,0,3.45);
   h_energy_tot->SetBinContent(2,1715);
   h_energy_tot->SetBinContent(3,3737);
   h_energy_tot->SetBinContent(4,4026);
   h_energy_tot->SetBinContent(5,5153);
   h_energy_tot->SetBinContent(6,5810);
   h_energy_tot->SetBinContent(7,5939);
   h_energy_tot->SetBinContent(8,5774);
   h_energy_tot->SetBinContent(9,5809);
   h_energy_tot->SetBinContent(10,5468);
   h_energy_tot->SetBinContent(11,5699);
   h_energy_tot->SetBinContent(12,5548);
   h_energy_tot->SetBinContent(13,5554);
   h_energy_tot->SetBinContent(14,5181);
   h_energy_tot->SetBinContent(15,5033);
   h_energy_tot->SetBinContent(16,4697);
   h_energy_tot->SetBinContent(17,4522);
   h_energy_tot->SetBinContent(18,4263);
   h_energy_tot->SetBinContent(19,3842);
   h_energy_tot->SetBinContent(20,3815);
   h_energy_tot->SetBinContent(21,3584);
   h_energy_tot->SetBinContent(22,3412);
   h_energy_tot->SetBinContent(23,3195);
   h_energy_tot->SetBinContent(24,3020);
   h_energy_tot->SetBinContent(25,2741);
   h_energy_tot->SetBinContent(26,2647);
   h_energy_tot->SetBinContent(27,2408);
   h_energy_tot->SetBinContent(28,2262);
   h_energy_tot->SetBinContent(29,2117);
   h_energy_tot->SetBinContent(30,1963);
   h_energy_tot->SetBinContent(31,1774);
   h_energy_tot->SetBinContent(32,1612);
   h_energy_tot->SetBinContent(33,1470);
   h_energy_tot->SetBinContent(34,1410);
   h_energy_tot->SetBinContent(35,1336);
   h_energy_tot->SetBinContent(36,1313);
   h_energy_tot->SetBinContent(37,1160);
   h_energy_tot->SetBinContent(38,1069);
   h_energy_tot->SetBinContent(39,935);
   h_energy_tot->SetBinContent(40,845);
   h_energy_tot->SetBinContent(41,775);
   h_energy_tot->SetBinContent(42,746);
   h_energy_tot->SetBinContent(43,734);
   h_energy_tot->SetBinContent(44,654);
   h_energy_tot->SetBinContent(45,654);
   h_energy_tot->SetBinContent(46,661);
   h_energy_tot->SetBinContent(47,602);
   h_energy_tot->SetBinContent(48,574);
   h_energy_tot->SetBinContent(49,580);
   h_energy_tot->SetBinContent(50,566);
   h_energy_tot->SetBinContent(51,499);
   h_energy_tot->SetBinContent(52,447);
   h_energy_tot->SetBinContent(53,500);
   h_energy_tot->SetBinContent(54,389);
   h_energy_tot->SetBinContent(55,413);
   h_energy_tot->SetBinContent(56,399);
   h_energy_tot->SetBinContent(57,349);
   h_energy_tot->SetBinContent(58,380);
   h_energy_tot->SetBinContent(59,344);
   h_energy_tot->SetBinContent(60,318);
   h_energy_tot->SetBinContent(61,316);
   h_energy_tot->SetBinContent(62,315);
   h_energy_tot->SetBinContent(63,247);
   h_energy_tot->SetBinContent(64,222);
   h_energy_tot->SetBinContent(65,268);
   h_energy_tot->SetBinContent(66,224);
   h_energy_tot->SetBinContent(67,184);
   h_energy_tot->SetBinContent(68,205);
   h_energy_tot->SetBinContent(69,171);
   h_energy_tot->SetBinContent(70,180);
   h_energy_tot->SetBinContent(71,173);
   h_energy_tot->SetBinContent(72,149);
   h_energy_tot->SetBinContent(73,95);
   h_energy_tot->SetBinContent(74,122);
   h_energy_tot->SetBinContent(75,94);
   h_energy_tot->SetBinContent(76,90);
   h_energy_tot->SetBinContent(77,80);
   h_energy_tot->SetBinContent(78,78);
   h_energy_tot->SetBinContent(79,59);
   h_energy_tot->SetBinContent(80,45);
   h_energy_tot->SetBinContent(81,48);
   h_energy_tot->SetBinContent(82,40);
   h_energy_tot->SetBinContent(83,41);
   h_energy_tot->SetBinContent(84,28);
   h_energy_tot->SetBinContent(85,25);
   h_energy_tot->SetBinContent(86,13);
   h_energy_tot->SetBinContent(87,8);
   h_energy_tot->SetBinContent(88,9);
   h_energy_tot->SetBinContent(89,6);
   h_energy_tot->SetBinContent(90,5);
   h_energy_tot->SetBinContent(91,4);
   h_energy_tot->SetBinContent(92,3);
   h_energy_tot->SetEntries(145989);
   h_energy_tot->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 145989 ");
   text = ptstats->AddText("Mean  = 0.6703");
   text = ptstats->AddText("RMS   = 0.5048");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_energy_tot->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_energy_tot);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_energy_tot->SetLineColor(ci);
   h_energy_tot->GetXaxis()->SetTitle("_energy");
   h_energy_tot->GetXaxis()->SetRange(1,100);
   h_energy_tot->GetXaxis()->SetLabelFont(42);
   h_energy_tot->GetXaxis()->SetLabelSize(0.035);
   h_energy_tot->GetXaxis()->SetTitleSize(0.035);
   h_energy_tot->GetXaxis()->SetTitleFont(42);
   h_energy_tot->GetYaxis()->SetLabelFont(42);
   h_energy_tot->GetYaxis()->SetLabelSize(0.035);
   h_energy_tot->GetYaxis()->SetTitleSize(0.035);
   h_energy_tot->GetYaxis()->SetTitleFont(42);
   h_energy_tot->GetZaxis()->SetLabelFont(42);
   h_energy_tot->GetZaxis()->SetLabelSize(0.035);
   h_energy_tot->GetZaxis()->SetTitleSize(0.035);
   h_energy_tot->GetZaxis()->SetTitleFont(42);
   h_energy_tot->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("_energy {_length < 3500 && _calo_impact != 5}");
   pt->Draw();
   c_energy_tot->Modified();
   c_energy_tot->cd();
   c_energy_tot->SetSelected(c_energy_tot);

   
   
   TCanvas *c_energy_no_negative_charge = new TCanvas("c_energy_no_negative_charge", "c_energy_no_negative_charge",11,34,700,500);
   c_energy_no_negative_charge->Range(-0.43125,-261.5813,3.88125,2354.231);
   c_energy_no_negative_charge->SetFillColor(0);
   c_energy_no_negative_charge->SetBorderMode(0);
   c_energy_no_negative_charge->SetBorderSize(2);
   c_energy_no_negative_charge->SetFrameBorderMode(0);
   c_energy_no_negative_charge->SetFrameBorderMode(0);
   
   TH1F *h_energy_no_negative_charge = new TH1F("h_energy_no_negative_charge","_energy",100,0,3.45);
   h_energy_no_negative_charge->SetBinContent(2,835);
   h_energy_no_negative_charge->SetBinContent(3,1570);
   h_energy_no_negative_charge->SetBinContent(4,1581);
   h_energy_no_negative_charge->SetBinContent(5,1901);
   h_energy_no_negative_charge->SetBinContent(6,1993);
   h_energy_no_negative_charge->SetBinContent(7,1850);
   h_energy_no_negative_charge->SetBinContent(8,1774);
   h_energy_no_negative_charge->SetBinContent(9,1724);
   h_energy_no_negative_charge->SetBinContent(10,1549);
   h_energy_no_negative_charge->SetBinContent(11,1576);
   h_energy_no_negative_charge->SetBinContent(12,1511);
   h_energy_no_negative_charge->SetBinContent(13,1503);
   h_energy_no_negative_charge->SetBinContent(14,1393);
   h_energy_no_negative_charge->SetBinContent(15,1353);
   h_energy_no_negative_charge->SetBinContent(16,1160);
   h_energy_no_negative_charge->SetBinContent(17,1100);
   h_energy_no_negative_charge->SetBinContent(18,1075);
   h_energy_no_negative_charge->SetBinContent(19,969);
   h_energy_no_negative_charge->SetBinContent(20,945);
   h_energy_no_negative_charge->SetBinContent(21,901);
   h_energy_no_negative_charge->SetBinContent(22,808);
   h_energy_no_negative_charge->SetBinContent(23,758);
   h_energy_no_negative_charge->SetBinContent(24,747);
   h_energy_no_negative_charge->SetBinContent(25,705);
   h_energy_no_negative_charge->SetBinContent(26,676);
   h_energy_no_negative_charge->SetBinContent(27,605);
   h_energy_no_negative_charge->SetBinContent(28,579);
   h_energy_no_negative_charge->SetBinContent(29,599);
   h_energy_no_negative_charge->SetBinContent(30,503);
   h_energy_no_negative_charge->SetBinContent(31,469);
   h_energy_no_negative_charge->SetBinContent(32,450);
   h_energy_no_negative_charge->SetBinContent(33,402);
   h_energy_no_negative_charge->SetBinContent(34,387);
   h_energy_no_negative_charge->SetBinContent(35,375);
   h_energy_no_negative_charge->SetBinContent(36,365);
   h_energy_no_negative_charge->SetBinContent(37,319);
   h_energy_no_negative_charge->SetBinContent(38,299);
   h_energy_no_negative_charge->SetBinContent(39,260);
   h_energy_no_negative_charge->SetBinContent(40,247);
   h_energy_no_negative_charge->SetBinContent(41,223);
   h_energy_no_negative_charge->SetBinContent(42,220);
   h_energy_no_negative_charge->SetBinContent(43,188);
   h_energy_no_negative_charge->SetBinContent(44,185);
   h_energy_no_negative_charge->SetBinContent(45,203);
   h_energy_no_negative_charge->SetBinContent(46,188);
   h_energy_no_negative_charge->SetBinContent(47,182);
   h_energy_no_negative_charge->SetBinContent(48,157);
   h_energy_no_negative_charge->SetBinContent(49,183);
   h_energy_no_negative_charge->SetBinContent(50,169);
   h_energy_no_negative_charge->SetBinContent(51,124);
   h_energy_no_negative_charge->SetBinContent(52,108);
   h_energy_no_negative_charge->SetBinContent(53,146);
   h_energy_no_negative_charge->SetBinContent(54,97);
   h_energy_no_negative_charge->SetBinContent(55,121);
   h_energy_no_negative_charge->SetBinContent(56,104);
   h_energy_no_negative_charge->SetBinContent(57,89);
   h_energy_no_negative_charge->SetBinContent(58,111);
   h_energy_no_negative_charge->SetBinContent(59,95);
   h_energy_no_negative_charge->SetBinContent(60,87);
   h_energy_no_negative_charge->SetBinContent(61,106);
   h_energy_no_negative_charge->SetBinContent(62,111);
   h_energy_no_negative_charge->SetBinContent(63,78);
   h_energy_no_negative_charge->SetBinContent(64,62);
   h_energy_no_negative_charge->SetBinContent(65,79);
   h_energy_no_negative_charge->SetBinContent(66,68);
   h_energy_no_negative_charge->SetBinContent(67,45);
   h_energy_no_negative_charge->SetBinContent(68,44);
   h_energy_no_negative_charge->SetBinContent(69,37);
   h_energy_no_negative_charge->SetBinContent(70,39);
   h_energy_no_negative_charge->SetBinContent(71,39);
   h_energy_no_negative_charge->SetBinContent(72,34);
   h_energy_no_negative_charge->SetBinContent(73,28);
   h_energy_no_negative_charge->SetBinContent(74,31);
   h_energy_no_negative_charge->SetBinContent(75,28);
   h_energy_no_negative_charge->SetBinContent(76,35);
   h_energy_no_negative_charge->SetBinContent(77,25);
   h_energy_no_negative_charge->SetBinContent(78,22);
   h_energy_no_negative_charge->SetBinContent(79,15);
   h_energy_no_negative_charge->SetBinContent(80,11);
   h_energy_no_negative_charge->SetBinContent(81,17);
   h_energy_no_negative_charge->SetBinContent(82,11);
   h_energy_no_negative_charge->SetBinContent(83,12);
   h_energy_no_negative_charge->SetBinContent(84,7);
   h_energy_no_negative_charge->SetBinContent(85,15);
   h_energy_no_negative_charge->SetBinContent(86,4);
   h_energy_no_negative_charge->SetBinContent(87,1);
   h_energy_no_negative_charge->SetBinContent(88,2);
   h_energy_no_negative_charge->SetBinContent(89,2);
   h_energy_no_negative_charge->SetBinContent(90,2);
   h_energy_no_negative_charge->SetBinContent(91,1);
   h_energy_no_negative_charge->SetBinContent(92,2);
   h_energy_no_negative_charge->SetEntries(41809);
   h_energy_no_negative_charge->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 41809  ");
   text = ptstats->AddText("Mean  = 0.6374");
   text = ptstats->AddText("RMS   = 0.5152");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_energy_no_negative_charge->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_energy_no_negative_charge);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_energy_no_negative_charge->SetLineColor(ci);
   h_energy_no_negative_charge->GetXaxis()->SetTitle("_energy");
   h_energy_no_negative_charge->GetXaxis()->SetRange(1,100);
   h_energy_no_negative_charge->GetXaxis()->SetLabelFont(42);
   h_energy_no_negative_charge->GetXaxis()->SetLabelSize(0.035);
   h_energy_no_negative_charge->GetXaxis()->SetTitleSize(0.035);
   h_energy_no_negative_charge->GetXaxis()->SetTitleFont(42);
   h_energy_no_negative_charge->GetYaxis()->SetLabelFont(42);
   h_energy_no_negative_charge->GetYaxis()->SetLabelSize(0.035);
   h_energy_no_negative_charge->GetYaxis()->SetTitleSize(0.035);
   h_energy_no_negative_charge->GetYaxis()->SetTitleFont(42);
   h_energy_no_negative_charge->GetZaxis()->SetLabelFont(42);
   h_energy_no_negative_charge->GetZaxis()->SetLabelSize(0.035);
   h_energy_no_negative_charge->GetZaxis()->SetTitleSize(0.035);
   h_energy_no_negative_charge->GetZaxis()->SetTitleFont(42);
   h_energy_no_negative_charge->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("_energy");
   pt->Draw();
   c_energy_no_negative_charge->Modified();
   c_energy_no_negative_charge->cd();
   c_energy_no_negative_charge->SetSelected(c_energy_no_negative_charge);


   TCanvas *c_5 = new TCanvas("c_5", "c_5",11,34,700,500);
   c_5->Range(-100,-1981.481,3400,17833.33);
   c_5->SetFillColor(0);
   c_5->SetBorderMode(0);
   c_5->SetBorderSize(2);
   c_5->SetFrameBorderMode(0);
   c_5->SetFrameBorderMode(0);
   
   TH1F * h_clone_energy = h_energy_no_negative_charge->Clone();
   h_clone_energy->Sumw2();
   h_energy_tot->Sumw2();
   h_clone_energy->Divide(h_energy_tot);
   h_clone_energy->SetMarkerStyle(8);
   h_clone_energy->SetLineColor(kBlack);
   h_clone_energy->SetLineWidth(2);
   h_clone_energy->GetYaxis()->SetTitle("Charge confusion");
   h_clone_energy->GetXaxis()->SetTitle("E_{electron} [MeV]");
   h_clone_energy->GetXaxis()->SetLabelSize(0.05);
   h_clone_energy->GetYaxis()->SetLabelSize(0.05);
   h_clone_energy->GetXaxis()->SetTitleSize(0.05);
   h_clone_energy->GetYaxis()->SetTitleSize(0.05);
   h_clone_energy->GetYaxis()->SetTitleOffset(1.3);
   h_clone_energy->GetYaxis()->SetRangeUser(0,0.6);
   
   c_5->cd();
   c_5->SetGridx();
   c_5->SetGridy();
   h_clone_energy->Draw();
   c_5->Update();   
   
   
   

   

   
   
   

}
