charge_confusion_source()  {

   TCanvas *c_length_tot = new TCanvas("c_length_tot", "c_length_tot",10,10,700,500);
   c_length_tot->Range(-100,-1981.481,3400,17833.33);
   c_length_tot->SetFillColor(0);
   c_length_tot->SetBorderMode(0);
   c_length_tot->SetBorderSize(2);
   c_length_tot->SetFrameBorderMode(0);
   c_length_tot->SetFrameBorderMode(0);
   
   TH1F *h_length_tot = new TH1F("h_length_tot","_length tot",100,250,3050);
   h_length_tot->SetBinContent(8,14661);
   h_length_tot->SetBinContent(9,15097);
   h_length_tot->SetBinContent(10,12682);
   h_length_tot->SetBinContent(11,10772);
   h_length_tot->SetBinContent(12,9575);
   h_length_tot->SetBinContent(13,8035);
   h_length_tot->SetBinContent(14,6953);
   h_length_tot->SetBinContent(15,5945);
   h_length_tot->SetBinContent(16,5279);
   h_length_tot->SetBinContent(17,4482);
   h_length_tot->SetBinContent(18,4027);
   h_length_tot->SetBinContent(19,3478);
   h_length_tot->SetBinContent(20,3029);
   h_length_tot->SetBinContent(21,2769);
   h_length_tot->SetBinContent(22,2346);
   h_length_tot->SetBinContent(23,2107);
   h_length_tot->SetBinContent(24,1906);
   h_length_tot->SetBinContent(25,1586);
   h_length_tot->SetBinContent(26,1439);
   h_length_tot->SetBinContent(27,1238);
   h_length_tot->SetBinContent(28,1124);
   h_length_tot->SetBinContent(29,979);
   h_length_tot->SetBinContent(30,875);
   h_length_tot->SetBinContent(31,700);
   h_length_tot->SetBinContent(32,639);
   h_length_tot->SetBinContent(33,548);
   h_length_tot->SetBinContent(34,499);
   h_length_tot->SetBinContent(35,431);
   h_length_tot->SetBinContent(36,373);
   h_length_tot->SetBinContent(37,328);
   h_length_tot->SetBinContent(38,285);
   h_length_tot->SetBinContent(39,267);
   h_length_tot->SetBinContent(40,235);
   h_length_tot->SetBinContent(41,200);
   h_length_tot->SetBinContent(42,188);
   h_length_tot->SetBinContent(43,149);
   h_length_tot->SetBinContent(44,132);
   h_length_tot->SetBinContent(45,105);
   h_length_tot->SetBinContent(46,104);
   h_length_tot->SetBinContent(47,97);
   h_length_tot->SetBinContent(48,88);
   h_length_tot->SetBinContent(49,71);
   h_length_tot->SetBinContent(50,63);
   h_length_tot->SetBinContent(51,55);
   h_length_tot->SetBinContent(52,57);
   h_length_tot->SetBinContent(53,46);
   h_length_tot->SetBinContent(54,32);
   h_length_tot->SetBinContent(55,41);
   h_length_tot->SetBinContent(56,36);
   h_length_tot->SetBinContent(57,36);
   h_length_tot->SetBinContent(58,19);
   h_length_tot->SetBinContent(59,35);
   h_length_tot->SetBinContent(60,18);
   h_length_tot->SetBinContent(61,23);
   h_length_tot->SetBinContent(62,18);
   h_length_tot->SetBinContent(63,13);
   h_length_tot->SetBinContent(64,3);
   h_length_tot->SetBinContent(65,14);
   h_length_tot->SetBinContent(66,6);
   h_length_tot->SetBinContent(67,8);
   h_length_tot->SetBinContent(68,6);
   h_length_tot->SetBinContent(69,8);
   h_length_tot->SetBinContent(70,6);
   h_length_tot->SetBinContent(71,6);
   h_length_tot->SetBinContent(72,5);
   h_length_tot->SetBinContent(73,5);
   h_length_tot->SetBinContent(74,3);
   h_length_tot->SetBinContent(75,5);
   h_length_tot->SetBinContent(76,5);
   h_length_tot->SetBinContent(77,7);
   h_length_tot->SetBinContent(78,3);
   h_length_tot->SetBinContent(79,3);
   h_length_tot->SetBinContent(80,4);
   h_length_tot->SetBinContent(81,2);
   h_length_tot->SetBinContent(82,1);
   h_length_tot->SetBinContent(83,1);
   h_length_tot->SetBinContent(85,2);
   h_length_tot->SetBinContent(89,1);
   h_length_tot->SetBinContent(90,1);
   h_length_tot->SetBinContent(91,1);
   h_length_tot->SetBinContent(92,1);
   h_length_tot->SetBinContent(93,1);
   h_length_tot->SetEntries(126423);
   h_length_tot->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 126423 ");
   text = ptstats->AddText("Mean  =  656.2");
   text = ptstats->AddText("RMS   =  214.9");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_length_tot->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_length_tot);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_length_tot->SetLineColor(ci);
   h_length_tot->GetXaxis()->SetTitle("Length_{e-} [mm]");
   h_length_tot->GetXaxis()->SetRange(1,100);
   h_length_tot->GetXaxis()->SetLabelFont(42);
   h_length_tot->GetXaxis()->SetLabelSize(0.035);
   h_length_tot->GetXaxis()->SetTitleSize(0.035);
   h_length_tot->GetXaxis()->SetTitleFont(42);
   h_length_tot->GetYaxis()->SetLabelFont(42);
   h_length_tot->GetYaxis()->SetLabelSize(0.035);
   h_length_tot->GetYaxis()->SetTitleSize(0.035);
   h_length_tot->GetYaxis()->SetTitleFont(42);
   h_length_tot->GetZaxis()->SetLabelFont(42);
   h_length_tot->GetZaxis()->SetLabelSize(0.035);
   h_length_tot->GetZaxis()->SetTitleSize(0.035);
   h_length_tot->GetZaxis()->SetTitleFont(42);
   h_length_tot->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("_length tot");
   pt->Draw();
   c_length_tot->Modified();
   c_length_tot->cd();
   c_length_tot->SetSelected(c_length_tot);
   

   
   
    
   
   TCanvas *c_length_no_neg_charge = new TCanvas("c_length_no_neg_charge", "c_length_no_neg_charge",10,30,700,500);
   c_length_no_neg_charge->Range(-87.50003,-170.2313,3287.5,1532.081);
   c_length_no_neg_charge->SetFillColor(0);
   c_length_no_neg_charge->SetBorderMode(0);
   c_length_no_neg_charge->SetBorderSize(2);
   c_length_no_neg_charge->SetFrameBorderMode(0);
   c_length_no_neg_charge->SetFrameBorderMode(0);
   
   TH1F *h_length_no_neg_charge = new TH1F("h_length_no_neg_charge","length no neg charge",100,250,2950);
   h_length_no_neg_charge->SetBinContent(8,932);
   h_length_no_neg_charge->SetBinContent(9,1297);
   h_length_no_neg_charge->SetBinContent(10,1053);
   h_length_no_neg_charge->SetBinContent(11,854);
   h_length_no_neg_charge->SetBinContent(12,795);
   h_length_no_neg_charge->SetBinContent(13,658);
   h_length_no_neg_charge->SetBinContent(14,621);
   h_length_no_neg_charge->SetBinContent(15,510);
   h_length_no_neg_charge->SetBinContent(16,406);
   h_length_no_neg_charge->SetBinContent(17,396);
   h_length_no_neg_charge->SetBinContent(18,325);
   h_length_no_neg_charge->SetBinContent(19,281);
   h_length_no_neg_charge->SetBinContent(20,226);
   h_length_no_neg_charge->SetBinContent(21,184);
   h_length_no_neg_charge->SetBinContent(22,195);
   h_length_no_neg_charge->SetBinContent(23,164);
   h_length_no_neg_charge->SetBinContent(24,154);
   h_length_no_neg_charge->SetBinContent(25,131);
   h_length_no_neg_charge->SetBinContent(26,117);
   h_length_no_neg_charge->SetBinContent(27,94);
   h_length_no_neg_charge->SetBinContent(28,86);
   h_length_no_neg_charge->SetBinContent(29,85);
   h_length_no_neg_charge->SetBinContent(30,84);
   h_length_no_neg_charge->SetBinContent(31,68);
   h_length_no_neg_charge->SetBinContent(32,54);
   h_length_no_neg_charge->SetBinContent(33,50);
   h_length_no_neg_charge->SetBinContent(34,39);
   h_length_no_neg_charge->SetBinContent(35,34);
   h_length_no_neg_charge->SetBinContent(36,46);
   h_length_no_neg_charge->SetBinContent(37,28);
   h_length_no_neg_charge->SetBinContent(38,39);
   h_length_no_neg_charge->SetBinContent(39,29);
   h_length_no_neg_charge->SetBinContent(40,34);
   h_length_no_neg_charge->SetBinContent(41,24);
   h_length_no_neg_charge->SetBinContent(42,15);
   h_length_no_neg_charge->SetBinContent(43,21);
   h_length_no_neg_charge->SetBinContent(44,14);
   h_length_no_neg_charge->SetBinContent(45,14);
   h_length_no_neg_charge->SetBinContent(46,8);
   h_length_no_neg_charge->SetBinContent(47,9);
   h_length_no_neg_charge->SetBinContent(48,12);
   h_length_no_neg_charge->SetBinContent(49,15);
   h_length_no_neg_charge->SetBinContent(50,6);
   h_length_no_neg_charge->SetBinContent(51,8);
   h_length_no_neg_charge->SetBinContent(52,11);
   h_length_no_neg_charge->SetBinContent(53,5);
   h_length_no_neg_charge->SetBinContent(54,2);
   h_length_no_neg_charge->SetBinContent(55,4);
   h_length_no_neg_charge->SetBinContent(57,5);
   h_length_no_neg_charge->SetBinContent(58,4);
   h_length_no_neg_charge->SetBinContent(59,4);
   h_length_no_neg_charge->SetBinContent(60,4);
   h_length_no_neg_charge->SetBinContent(61,3);
   h_length_no_neg_charge->SetBinContent(62,4);
   h_length_no_neg_charge->SetBinContent(63,2);
   h_length_no_neg_charge->SetBinContent(64,3);
   h_length_no_neg_charge->SetBinContent(65,2);
   h_length_no_neg_charge->SetBinContent(66,1);
   h_length_no_neg_charge->SetBinContent(67,2);
   h_length_no_neg_charge->SetBinContent(69,3);
   h_length_no_neg_charge->SetBinContent(71,1);
   h_length_no_neg_charge->SetBinContent(72,2);
   h_length_no_neg_charge->SetBinContent(74,2);
   h_length_no_neg_charge->SetBinContent(78,1);
   h_length_no_neg_charge->SetBinContent(88,1);
   h_length_no_neg_charge->SetBinContent(93,1);
   h_length_no_neg_charge->SetEntries(10282);
   h_length_no_neg_charge->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 10282  ");
   text = ptstats->AddText("Mean  =  655.9");
   text = ptstats->AddText("RMS   =  227.6");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_length_no_neg_charge->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_length_no_neg_charge);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_length_no_neg_charge->SetLineColor(ci);
   h_length_no_neg_charge->GetXaxis()->SetTitle("Electron length[mm]");
   h_length_no_neg_charge->GetXaxis()->SetRange(1,100);
   h_length_no_neg_charge->GetXaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetXaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetXaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetXaxis()->SetTitleFont(42);
   h_length_no_neg_charge->GetYaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetYaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetYaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetYaxis()->SetTitleFont(42);
   h_length_no_neg_charge->GetZaxis()->SetLabelFont(42);
   h_length_no_neg_charge->GetZaxis()->SetLabelSize(0.035);
   h_length_no_neg_charge->GetZaxis()->SetTitleSize(0.035);
   h_length_no_neg_charge->GetZaxis()->SetTitleFont(42);
   h_length_no_neg_charge->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("length");
   pt->Draw();
   c_length_no_neg_charge->Modified();
   c_length_no_neg_charge->cd();
   c_length_no_neg_charge->SetSelected(c_length_no_neg_charge);
   

   /// Compute the ratio between the 2 curves
    
   TCanvas *c_3 = new TCanvas("c_3", "c_3",11,34,700,500);
   c_3->Range(-100,-1981.481,3400,17833.33);
   c_3->SetFillColor(0);
   c_3->SetBorderMode(0);
   c_3->SetBorderSize(2);
   c_3->SetFrameBorderMode(0);
   c_3->SetFrameBorderMode(0);
   
   TH1F * h_clone_length = h_length_no_neg_charge->Clone(); 
  
   h_clone_length->Sumw2();
   h_length_tot->Sumw2();   
   h_clone_length->Divide(h_length_tot);
   h_clone_length->SetMarkerStyle(8);
   h_clone_length->SetLineColor(kBlack);
   h_clone_length->SetLineWidth(2);
   h_clone_length->GetYaxis()->SetTitle("Charge confusion");
   h_clone_length->GetXaxis()->SetLabelSize(0.05);
   h_clone_length->GetYaxis()->SetLabelSize(0.05);
   h_clone_length->GetXaxis()->SetTitleSize(0.05);
   h_clone_length->GetYaxis()->SetTitleSize(0.05);
   h_clone_length->GetYaxis()->SetTitleOffset(1.3);
   h_clone_length->GetYaxis()->SetRangeUser(0,1.1);
  
   c_3->cd();
   c_3->SetGridx();
   c_3->SetGridy();
   h_clone_length->Draw();
   c_3->Update();


   TCanvas *c_length = new TCanvas("c_length", "c_length",50,50,700,500);
   c_length->Range(-100,-1981.481,3400,17833.33);
   c_length->SetFillColor(0);
   c_length->SetBorderMode(0);
   c_length->SetBorderSize(2);
   c_length->SetFrameBorderMode(0);
   c_length->SetFrameBorderMode(0);
   
   c_length->cd();
   h_length_tot->Draw();
   h_length_no_neg_charge->Draw("same");
   c_length->Update();



/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////
/////////////////////////////////////////////////

   TCanvas *c_energy_tot = new TCanvas("c_energy_tot", "c_energy_tot",11,50,700,500);
   c_energy_tot->Range(-0.425,-631.3125,3.825,5681.813);
   c_energy_tot->SetFillColor(0);
   c_energy_tot->SetBorderMode(0);
   c_energy_tot->SetBorderSize(2);
   c_energy_tot->SetFrameBorderMode(0);
   c_energy_tot->SetFrameBorderMode(0);
   
   TH1F *h_energy_tot = new TH1F("length","energy",100,0,3.4);
   h_energy_tot->SetBinContent(2,861);
   h_energy_tot->SetBinContent(3,2049);
   h_energy_tot->SetBinContent(4,2399);
   h_energy_tot->SetBinContent(5,3421);
   h_energy_tot->SetBinContent(6,4027);
   h_energy_tot->SetBinContent(7,4511);
   h_energy_tot->SetBinContent(8,4553);
   h_energy_tot->SetBinContent(9,4663);
   h_energy_tot->SetBinContent(10,4719);
   h_energy_tot->SetBinContent(11,4797);
   h_energy_tot->SetBinContent(12,4690);
   h_energy_tot->SetBinContent(13,4531);
   h_energy_tot->SetBinContent(14,4810);
   h_energy_tot->SetBinContent(15,4457);
   h_energy_tot->SetBinContent(16,4362);
   h_energy_tot->SetBinContent(17,4033);
   h_energy_tot->SetBinContent(18,3918);
   h_energy_tot->SetBinContent(19,3649);
   h_energy_tot->SetBinContent(20,3728);
   h_energy_tot->SetBinContent(21,3303);
   h_energy_tot->SetBinContent(22,3287);
   h_energy_tot->SetBinContent(23,2976);
   h_energy_tot->SetBinContent(24,2817);
   h_energy_tot->SetBinContent(25,2582);
   h_energy_tot->SetBinContent(26,2448);
   h_energy_tot->SetBinContent(27,2416);
   h_energy_tot->SetBinContent(28,2080);
   h_energy_tot->SetBinContent(29,2113);
   h_energy_tot->SetBinContent(30,1864);
   h_energy_tot->SetBinContent(31,1749);
   h_energy_tot->SetBinContent(32,1555);
   h_energy_tot->SetBinContent(33,1489);
   h_energy_tot->SetBinContent(34,1336);
   h_energy_tot->SetBinContent(35,1293);
   h_energy_tot->SetBinContent(36,1176);
   h_energy_tot->SetBinContent(37,1139);
   h_energy_tot->SetBinContent(38,1080);
   h_energy_tot->SetBinContent(39,950);
   h_energy_tot->SetBinContent(40,878);
   h_energy_tot->SetBinContent(41,701);
   h_energy_tot->SetBinContent(42,700);
   h_energy_tot->SetBinContent(43,626);
   h_energy_tot->SetBinContent(44,612);
   h_energy_tot->SetBinContent(45,593);
   h_energy_tot->SetBinContent(46,646);
   h_energy_tot->SetBinContent(47,558);
   h_energy_tot->SetBinContent(48,594);
   h_energy_tot->SetBinContent(49,529);
   h_energy_tot->SetBinContent(50,477);
   h_energy_tot->SetBinContent(51,464);
   h_energy_tot->SetBinContent(52,428);
   h_energy_tot->SetBinContent(53,415);
   h_energy_tot->SetBinContent(54,442);
   h_energy_tot->SetBinContent(55,369);
   h_energy_tot->SetBinContent(56,331);
   h_energy_tot->SetBinContent(57,382);
   h_energy_tot->SetBinContent(58,354);
   h_energy_tot->SetBinContent(59,324);
   h_energy_tot->SetBinContent(60,326);
   h_energy_tot->SetBinContent(61,313);
   h_energy_tot->SetBinContent(62,292);
   h_energy_tot->SetBinContent(63,298);
   h_energy_tot->SetBinContent(64,264);
   h_energy_tot->SetBinContent(65,242);
   h_energy_tot->SetBinContent(66,266);
   h_energy_tot->SetBinContent(67,224);
   h_energy_tot->SetBinContent(68,182);
   h_energy_tot->SetBinContent(69,180);
   h_energy_tot->SetBinContent(70,166);
   h_energy_tot->SetBinContent(71,164);
   h_energy_tot->SetBinContent(72,143);
   h_energy_tot->SetBinContent(73,134);
   h_energy_tot->SetBinContent(74,116);
   h_energy_tot->SetBinContent(75,109);
   h_energy_tot->SetBinContent(76,110);
   h_energy_tot->SetBinContent(77,112);
   h_energy_tot->SetBinContent(78,80);
   h_energy_tot->SetBinContent(79,88);
   h_energy_tot->SetBinContent(80,67);
   h_energy_tot->SetBinContent(81,50);
   h_energy_tot->SetBinContent(82,52);
   h_energy_tot->SetBinContent(83,28);
   h_energy_tot->SetBinContent(84,39);
   h_energy_tot->SetBinContent(85,29);
   h_energy_tot->SetBinContent(86,27);
   h_energy_tot->SetBinContent(87,18);
   h_energy_tot->SetBinContent(88,24);
   h_energy_tot->SetBinContent(89,9);
   h_energy_tot->SetBinContent(90,7);
   h_energy_tot->SetBinContent(91,7);
   h_energy_tot->SetBinContent(92,4);
   h_energy_tot->SetEntries(126424);
   h_energy_tot->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 126424 ");
   text = ptstats->AddText("Mean  = 0.7118");
   text = ptstats->AddText("RMS   = 0.5105");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_energy_tot->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_energy_tot);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_energy_tot->SetLineColor(ci);
   h_energy_tot->GetXaxis()->SetTitle("E_{e} [MeV]");
   h_energy_tot->GetXaxis()->SetRange(1,100);
   h_energy_tot->GetXaxis()->SetLabelFont(42);
   h_energy_tot->GetXaxis()->SetLabelSize(0.035);
   h_energy_tot->GetXaxis()->SetTitleSize(0.035);
   h_energy_tot->GetXaxis()->SetTitleFont(42);
   h_energy_tot->GetYaxis()->SetLabelFont(42);
   h_energy_tot->GetYaxis()->SetLabelSize(0.035);
   h_energy_tot->GetYaxis()->SetTitleSize(0.035);
   h_energy_tot->GetYaxis()->SetTitleFont(42);
   h_energy_tot->GetZaxis()->SetLabelFont(42);
   h_energy_tot->GetZaxis()->SetLabelSize(0.035);
   h_energy_tot->GetZaxis()->SetTitleSize(0.035);
   h_energy_tot->GetZaxis()->SetTitleFont(42);
   h_energy_tot->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("_energy");
   pt->Draw();
   c_energy_tot->Modified();
   c_energy_tot->cd();
   c_energy_tot->SetSelected(c_energy_tot);
   
   
   
   TCanvas *c_energy_no_neg_charge = new TCanvas("c_energy_no_neg_charge", "c_energy_no_neg_charge",11,70,700,500);
   c_energy_no_neg_charge->Range(-0.41875,-66.28125,3.76875,596.5313);
   c_energy_no_neg_charge->SetFillColor(0);
   c_energy_no_neg_charge->SetBorderMode(0);
   c_energy_no_neg_charge->SetBorderSize(2);
   c_energy_no_neg_charge->SetFrameBorderMode(0);
   c_energy_no_neg_charge->SetFrameBorderMode(0);
   
   TH1F *h_energy_no_neg_charge = new TH1F("energy","energy",100,0,3.35);
   h_energy_no_neg_charge->SetBinContent(2,178);
   h_energy_no_neg_charge->SetBinContent(3,381);
   h_energy_no_neg_charge->SetBinContent(4,364);
   h_energy_no_neg_charge->SetBinContent(5,457);
   h_energy_no_neg_charge->SetBinContent(6,477);
   h_energy_no_neg_charge->SetBinContent(7,505);
   h_energy_no_neg_charge->SetBinContent(8,414);
   h_energy_no_neg_charge->SetBinContent(9,450);
   h_energy_no_neg_charge->SetBinContent(10,426);
   h_energy_no_neg_charge->SetBinContent(11,400);
   h_energy_no_neg_charge->SetBinContent(12,375);
   h_energy_no_neg_charge->SetBinContent(13,348);
   h_energy_no_neg_charge->SetBinContent(14,353);
   h_energy_no_neg_charge->SetBinContent(15,363);
   h_energy_no_neg_charge->SetBinContent(16,290);
   h_energy_no_neg_charge->SetBinContent(17,270);
   h_energy_no_neg_charge->SetBinContent(18,280);
   h_energy_no_neg_charge->SetBinContent(19,243);
   h_energy_no_neg_charge->SetBinContent(20,235);
   h_energy_no_neg_charge->SetBinContent(21,237);
   h_energy_no_neg_charge->SetBinContent(22,216);
   h_energy_no_neg_charge->SetBinContent(23,200);
   h_energy_no_neg_charge->SetBinContent(24,157);
   h_energy_no_neg_charge->SetBinContent(25,173);
   h_energy_no_neg_charge->SetBinContent(26,156);
   h_energy_no_neg_charge->SetBinContent(27,153);
   h_energy_no_neg_charge->SetBinContent(28,140);
   h_energy_no_neg_charge->SetBinContent(29,104);
   h_energy_no_neg_charge->SetBinContent(30,143);
   h_energy_no_neg_charge->SetBinContent(31,113);
   h_energy_no_neg_charge->SetBinContent(32,116);
   h_energy_no_neg_charge->SetBinContent(33,91);
   h_energy_no_neg_charge->SetBinContent(34,103);
   h_energy_no_neg_charge->SetBinContent(35,81);
   h_energy_no_neg_charge->SetBinContent(36,64);
   h_energy_no_neg_charge->SetBinContent(37,91);
   h_energy_no_neg_charge->SetBinContent(38,82);
   h_energy_no_neg_charge->SetBinContent(39,66);
   h_energy_no_neg_charge->SetBinContent(40,65);
   h_energy_no_neg_charge->SetBinContent(41,50);
   h_energy_no_neg_charge->SetBinContent(42,45);
   h_energy_no_neg_charge->SetBinContent(43,43);
   h_energy_no_neg_charge->SetBinContent(44,30);
   h_energy_no_neg_charge->SetBinContent(45,44);
   h_energy_no_neg_charge->SetBinContent(46,44);
   h_energy_no_neg_charge->SetBinContent(47,41);
   h_energy_no_neg_charge->SetBinContent(48,35);
   h_energy_no_neg_charge->SetBinContent(49,43);
   h_energy_no_neg_charge->SetBinContent(50,30);
   h_energy_no_neg_charge->SetBinContent(51,25);
   h_energy_no_neg_charge->SetBinContent(52,31);
   h_energy_no_neg_charge->SetBinContent(53,24);
   h_energy_no_neg_charge->SetBinContent(54,40);
   h_energy_no_neg_charge->SetBinContent(55,22);
   h_energy_no_neg_charge->SetBinContent(56,23);
   h_energy_no_neg_charge->SetBinContent(57,18);
   h_energy_no_neg_charge->SetBinContent(58,30);
   h_energy_no_neg_charge->SetBinContent(59,23);
   h_energy_no_neg_charge->SetBinContent(60,16);
   h_energy_no_neg_charge->SetBinContent(61,17);
   h_energy_no_neg_charge->SetBinContent(62,21);
   h_energy_no_neg_charge->SetBinContent(63,16);
   h_energy_no_neg_charge->SetBinContent(64,19);
   h_energy_no_neg_charge->SetBinContent(65,14);
   h_energy_no_neg_charge->SetBinContent(66,22);
   h_energy_no_neg_charge->SetBinContent(67,16);
   h_energy_no_neg_charge->SetBinContent(68,12);
   h_energy_no_neg_charge->SetBinContent(69,13);
   h_energy_no_neg_charge->SetBinContent(70,13);
   h_energy_no_neg_charge->SetBinContent(71,15);
   h_energy_no_neg_charge->SetBinContent(72,12);
   h_energy_no_neg_charge->SetBinContent(73,10);
   h_energy_no_neg_charge->SetBinContent(74,5);
   h_energy_no_neg_charge->SetBinContent(75,6);
   h_energy_no_neg_charge->SetBinContent(76,11);
   h_energy_no_neg_charge->SetBinContent(77,8);
   h_energy_no_neg_charge->SetBinContent(78,4);
   h_energy_no_neg_charge->SetBinContent(79,3);
   h_energy_no_neg_charge->SetBinContent(80,6);
   h_energy_no_neg_charge->SetBinContent(81,1);
   h_energy_no_neg_charge->SetBinContent(82,4);
   h_energy_no_neg_charge->SetBinContent(83,1);
   h_energy_no_neg_charge->SetBinContent(84,4);
   h_energy_no_neg_charge->SetBinContent(85,2);
   h_energy_no_neg_charge->SetBinContent(86,2);
   h_energy_no_neg_charge->SetBinContent(87,4);
   h_energy_no_neg_charge->SetBinContent(88,1);
   h_energy_no_neg_charge->SetBinContent(89,2);
   h_energy_no_neg_charge->SetBinContent(93,1);
   h_energy_no_neg_charge->SetEntries(10282);
   h_energy_no_neg_charge->SetDirectory(0);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("htemp");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 10282  ");
   text = ptstats->AddText("Mean  = 0.6144");
   text = ptstats->AddText("RMS   = 0.4994");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   h_energy_no_neg_charge->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(h_energy_no_neg_charge);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   h_energy_no_neg_charge->SetLineColor(ci);
   h_energy_no_neg_charge->GetXaxis()->SetTitle("E_{e} [MeV]");
   h_energy_no_neg_charge->GetXaxis()->SetRange(1,100);
   h_energy_no_neg_charge->GetXaxis()->SetLabelFont(42);
   h_energy_no_neg_charge->GetXaxis()->SetLabelSize(0.035);
   h_energy_no_neg_charge->GetXaxis()->SetTitleSize(0.035);
   h_energy_no_neg_charge->GetXaxis()->SetTitleFont(42);
   h_energy_no_neg_charge->GetYaxis()->SetLabelFont(42);
   h_energy_no_neg_charge->GetYaxis()->SetLabelSize(0.035);
   h_energy_no_neg_charge->GetYaxis()->SetTitleSize(0.035);
   h_energy_no_neg_charge->GetYaxis()->SetTitleFont(42);
   h_energy_no_neg_charge->GetZaxis()->SetLabelFont(42);
   h_energy_no_neg_charge->GetZaxis()->SetLabelSize(0.035);
   h_energy_no_neg_charge->GetZaxis()->SetTitleSize(0.035);
   h_energy_no_neg_charge->GetZaxis()->SetTitleFont(42);
   h_energy_no_neg_charge->Draw("");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("energy");
   pt->Draw();
   c_energy_no_neg_charge->Modified();
   c_energy_no_neg_charge->cd();
   c_energy_no_neg_charge->SetSelected(c_energy_no_neg_charge);

   
 //   TH1F * h_clone_length = new TH1F();
    
   TCanvas *c_5 = new TCanvas("c_5", "c_5",50,90,700,500);
   c_5->Range(-100,-1981.481,3400,17833.33);
   c_5->SetFillColor(0);
   c_5->SetBorderMode(0);
   c_5->SetBorderSize(2);
   c_5->SetFrameBorderMode(0);
   c_5->SetFrameBorderMode(0);
   
   TH1F * h_clone_energy = h_energy_no_neg_charge->Clone();
   h_clone_energy->Sumw2();
   h_energy_tot->Sumw2();
   h_clone_energy->Divide(h_energy_tot);
   
   h_clone_energy->SetMarkerStyle(8);
   h_clone_energy->SetLineColor(kBlack);
   h_clone_energy->SetLineWidth(2);
   h_clone_energy->GetYaxis()->SetTitle("Charge confusion");
   h_clone_energy->GetXaxis()->SetLabelSize(0.05);
   h_clone_energy->GetYaxis()->SetLabelSize(0.05);
   h_clone_energy->GetXaxis()->SetTitleSize(0.05);
   h_clone_energy->GetYaxis()->SetTitleSize(0.05);
   h_clone_energy->GetYaxis()->SetTitleOffset(1.3);
   h_clone_energy->GetYaxis()->SetRangeUser(0,0.5);
   c_5->cd();
   c_5->SetGridx();
   c_5->SetGridy();
   h_clone_energy->Draw();
   c_5->Update();   
}
